//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testdelete.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class childTab
    {
        public int Id { get; set; }
        public string PlanName { get; set; }
        public Nullable<int> parentID { get; set; }
    
        public virtual parentTab parentTab { get; set; }
    }
}
