//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testdelete.DbConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductEntities : DbContext
    {
        public ProductEntities()
            : base("name=ProductEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<childTab> childTabs { get; set; }
        public DbSet<Mark> Marks { get; set; }
        public DbSet<parentTab> parentTabs { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<productSet> productSets { get; set; }
        public DbSet<SchoolInfo> SchoolInfoes { get; set; }
        public DbSet<Student> Students { get; set; }
    }
}
