//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testdelete.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolInfo
    {
        public SchoolInfo()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public string ClassName { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
